apiVersion: v1
kind: Service
metadata:
  labels:
    app: time-service
  name: time-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: time-service
  type: NodePort

